
const DEPT_SHORTHAND = {
  "Anthropology": 'ANTH',
  "Bio Engin Small Scale Tech": 'BEST',
  "Biological Sciences": 'BIO',
  "Bioengineering": 'BIOE',
  "Chicano Chicana Studies": 'CCST',
  "Chemistry": 'CHEM',
  "Chinese": 'CHN',
  "Cognitive Science": 'COGS',
  "Critical Race & Ethnic Studies": 'CRES',
  "Community Research and Service": 'CRS',
  "Computer Science & Engineering": 'CSE',
  "Economics": 'ECON',
  "Elect. Engr. & Comp. Sci.": 'EECS',
  "English": 'ENG',
  "Engineering": 'ENGR',
  "Environmental Engineering": 'ENVE',
  "Environmental Systems (GR)": 'ES',
  "Earth Systems Science": 'ESS',
  "French": 'FRE',
  "Global Arts Studies Program": 'GASP',
  "History": 'HIST',
  "Interdisciplinary Humanities": 'IH',
  "Japanese": 'JPN',
  "Mathematics": 'MATH',
  "Mechanical Engineering": 'ME',
  "Management": 'MGMT',
  "Materials Science & Engr": 'MSE',
  "Natural Sciences Education": 'NSED',
  "Nat Sciences Undergrad Studies": 'NSUS',
  "Public Health": 'PH',
  "Philosophy": 'PHIL',
  "Physics": 'PHYS',
  "Political Science": 'POLI',
  "Psychology": 'PSY',
  "Quantitative & Systems Biology": 'QSB',
  "Sociology": 'SOC',
  "Spanish": 'SPAN',
  "World Heritage": 'WH',
  "Writing": 'WRI',
};

export { DEPT_SHORTHAND };
